import './globals.css'
import { Metadata } from 'next'
import Nav from './components/nav'
import Profil from './components/profil'

import { Providers } from "./providers";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faHouse, faGauge, faClipboard, faUser, faBookOpen } from "@fortawesome/free-solid-svg-icons";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

export const metadata: Metadata = {
  title: 'Sekolahku',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="">
        <Providers>
          <main className="h-screen dark text-foreground bg-background">
            <section className='flex flex-row'>
              <div className='basis-1/5'>
                <div className='pr-3'>
                  <Profil />
                  <Nav navLinks={[
                    { href: "/", name: "Home", icon: <FontAwesomeIcon className='px-1' icon={faHouse} /> },
                    { href: "/dashboard", name: "Dashboard", icon: <FontAwesomeIcon className='px-1' icon={faGauge} /> },
                    { href: "/absen", name: "Absen", icon: <FontAwesomeIcon className='px-1' icon={faClipboard} /> },
                    { href: "/user", name: "User", icon: <FontAwesomeIcon className='px-1' icon={faUser} /> },
                    { href: "/laporan", name: "Laporan", icon: <FontAwesomeIcon className='px-1' icon={faBookOpen} /> },
                  ]}></Nav>
                </div>
              </div>
              {children}
            </section>
          </main>
        </Providers>
      </body>
    </html >
  )
}
